FROM dev/rcamp
MAINTAINER Zebula Sampedro <sampedro@colorado.edu>

ENV RCAMP_DEBUG=True

# Install dev dependencies
RUN yum -y install nodejs npm && \
    yum -y install openssl pamtester fontconfig freetype freetype-devel fontconfig-devel libstdc++ && \
    npm install -g phantomjs-prebuilt && \
    pip install selenium==3.7.0

# Add test users for PAM auth
RUN useradd -M -p $(echo password | openssl passwd -1 -stdin) testuser1 && \
    useradd -M -p $(echo password | openssl passwd -1 -stdin) testuser2

WORKDIR /home/uwsgi/rcamp
