sudo: required

language: python

services:
  - docker

before_install:
- pip install --upgrade docker-compose
- cd rcamp
- docker build -t dev/rcamp --build-arg UWSGI_UID=$(id -u) --build-arg UWSGI_GID=$(id -u) .
- cd ..
- export RCAMP_PORT=9000
- docker-compose -f docker-compose.yml -f docker-compose.test-backends.yml -f docker-compose.dev.yml build
- docker-compose -f docker-compose.yml -f docker-compose.test-backends.yml -f docker-compose.dev.yml run --rm --service-ports rcamp-uwsgi bash -c 'sleep 30s && python manage.py migrate'
- docker-compose -f docker-compose.yml -f docker-compose.test-backends.yml -f docker-compose.dev.yml run --rm --service-ports rcamp-uwsgi bash -c 'python manage.py test'

install: true
script: true

notifications:
  email: false
  slack: "audd7JhHrzK3Z/Gu/zlmCyjrJ7ZLG48NUQilsyOJTh0DgQfDMJlSz0UFiOwSR+sXf3nqqH7wy9Njm9HLFRY7n/i+Hqm3dOOaCFLQgwf3MCmgPnNDr/Ksz0QbioyX2Nyj+JzbF5uKWkummGfKKMfostZp9tykXjt2gG9NasTtNcGXJ5cagjlyzx8EmS62agT91O0SZZ/reFOmVPN0q0n+DyJOVExMvSA9k+EbZV83n1O0Pxr5lWryOPh7TkxdiLQi3v2Ej9IS8RdV8a20TcX1Bx3lX5ef43+zjr3X/3EBbxjYGJlCLtMc/MmqGnnfdCrvm34QTTEjmAUAL6TSaRMejXUhfK+qfPlCP9ZPueMvS++hpOWig8Xlocrh6r5kzKJE77u5MbyLy9/Qot7Kv+1Wc27Xt0ZMixZ9JHc6FrzKIq088GhOXsyMIARlprr2mAWTcoVSMXXAfTz4MzqFT8EUja//Bu8Xd6ajfu48ItlfxdwurmZA59TDujU7UQakdGFw2y+2z/NiLbbhYGyZGVFAIZz60APmFTlNCS3Nmbc4R90bdY8l04kyDNlr52pVa+SQOtWE7rtPU6RL5xfCQGX2w7EpvUxlxTWj8OqkS+jqmL/GHsgN7QdljamYRiMspaA8l/jrsPUe+OG76yJIW2r9ANfu+8M/a4IrhL2Sh/jc8sw="
