version: "3.6"

services:
  test-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_PASSWORD=password
    volumes:
      - ./db:/var/lib/mysql

  test-ldap:
    image: researchcomputing/rc-test-ldap
    # build: ldap
