version: "3.6"

services:
  nginx:
    volumes:
      - certs:/etc/nginx/certs:ro
    depends_on:
      - cert-gen

  cert-gen:
    build:
      context: ./cert-gen
      args:
        - common_name=${HOSTNAME}
        - cert_name=rcamp
    volumes:
      - certs:/home/root/certs

  test-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=rcamp1712
    volumes:
      - ./db:/var/lib/mysql

  test-ldap:
    image: researchcomputing/rc-test-ldap
    # build: ldap

volumes:
  certs:
