version: "3.6"

services:
  rcamp-uwsgi:
    build:
      context: rcamp
      cache_from:
        - dev/rcamp
      dockerfile: Dockerfile.test
    environment:
      - RCAMP_DEBUG=True
      - RCAMP_UCB_LDAP_URI=${RCAMP_UCB_LDAP_URI}
      - RCAMP_UCB_LDAP_USER=${RCAMP_UCB_LDAP_USER}
      - RCAMP_UCB_LDAP_PASSWORD=${RCAMP_UCB_LDAP_PASSWORD}
      - RCAMP_CSU_LDAP_URI=${RCAMP_CSU_LDAP_URI}
      - RCAMP_CSU_LDAP_USER=${RCAMP_CSU_LDAP_USER}
      - RCAMP_CSU_LDAP_PASSWORD=${RCAMP_CSU_LDAP_PASSWORD}
    volumes:
      - ./rcamp/rcamp:/home/uwsgi/rcamp
      - ./rcamp/ldapdb:/home/uwsgi/ldapdb
    ports:
      - "${RCAMP_PORT}:9000"
    depends_on:
      - test-mysql
      - test-ldap
