"""
Django settings for rcamp project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j38e9!%8z#b=$=g87wzlb*+gqm0kc-6x7lb^_b6_zg1#(b*75s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'crispy_forms',
    'rest_framework',

    'ldapdb',
    'lib',
    'mailer',
    'accounts',
    'projects',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'rcamp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(os.path.dirname(os.path.abspath(__file__)),'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rcamp.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    # Test LDAP configuration
    'rcldap_test': {
        'ENGINE': 'ldapdb.backends.ldap',
        'NAME': 'ldap://localhost',
        'USER': 'cn=admin,dc=nodomain',
        'PASSWORD': 'test',
    },
    'culdap_test': {
        'ENGINE': 'ldapdb.backends.ldap',
        'NAME': 'ldap://localhost',
        'USER': 'cn=admin,dc=nodomain',
        'PASSWORD': 'test',
    },
}

LDAPCONFS = {
    'rcldap': {
        'server': DATABASES['rcldap_test']['NAME'],
        'bind_dn': DATABASES['rcldap_test']['USER'],
        'bind_pw': DATABASES['rcldap_test']['PASSWORD'],
        'base_dn': '',
        'people_dn': '',
        'ucb_dn': '',
        'csu_dn': '',
        'xsede_dn': '',
        'internal_dn': '',
        'group_dn': '',
    },
    'culdap': {
        'server': DATABASES['culdap_test']['NAME'],
        'bind_dn': DATABASES['culdap_test']['USER'],
        'bind_pw': DATABASES['culdap_test']['PASSWORD'],
        'base_dn': '',
        'group_dn': '',
        'people_dn': '',
    },
    'csuldap': {
        'server': DATABASES['culdap_test']['NAME'],
        'bind_dn': DATABASES['culdap_test']['USER'],
        'bind_pw': DATABASES['culdap_test']['PASSWORD'],
        'base_dn': '',
        'group_dn': '',
        'people_dn': '',
    },
}

DATABASE_ROUTERS = ['lib.router.LdapRouter',]

EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'lib.pam_backend.PamBackend',
)

LOGIN_URL = '/login'

LOGIN_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'rcamp','media','')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static')
STATICFILES_DIRS = (
    os.path.join(os.path.dirname(os.path.abspath(__file__)),'static'),
)

# Media files (User-uploaded files)
# https://docs.djangoproject.com/en/1.8/ref/settings/#media-root
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media','')

# GRAPPELLI ADMIN SETTINGS
GRAPPELLI_ADMIN_TITLE = 'RCAMP'

REST_FRAMEWORK = {}

PAM_SERVICES = {
    'default': 'login',
    'csu': 'csu'
}

LICENSE_GROUPS = {
    'ucb': 'ucb'
}

ORGANIZATION_INFO = {
    'ucb': {
        'long_name': 'University of Colorado Boulder',
        'suffix': None
    },
    'csu': {
        'long_name': 'Colorado State University',
        'suffix': 'colostate.edu'
    },
    'xsede': {
        'long_name': 'XSEDE',
        'suffix': 'xsede.org'
    },
    'internal': {
        'long_name': 'Research Computing - Administrative',
        'suffix': None
    }
}

try:
    from local_settings import *
except:
    pass
