# Generated by Django 2.2.28 on 2025-03-05 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_id', models.SlugField(blank=True, null=True, unique=True)),
                ('amount', models.BigIntegerField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expiration_notice_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_emails', lib.fields.ListField()),
                ('organization', models.CharField(choices=[('ucb', 'University of Colorado Boulder'), ('csu', 'Colorado State University'), ('xsede', 'XSEDE'), ('amc', 'AMC')], max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('project_id', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('parent_account', models.CharField(blank=True, max_length=24, null=True)),
                ('qos_addenda', models.CharField(blank=True, max_length=128, null=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('collaborators', models.ManyToManyField(related_name='collaborator_on', to=settings.AUTH_USER_MODEL)),
                ('managers', models.ManyToManyField(related_name='manager_on', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField(blank=True, null=True)),
                ('funding', models.TextField(blank=True, null=True)),
                ('proposal', models.FileField(blank=True, null=True, upload_to='proposals/%Y/%m/%d')),
                ('time_requested', models.BigIntegerField(blank=True, null=True)),
                ('amount_awarded', models.BigIntegerField(default=0)),
                ('disk_space', models.IntegerField(blank=True, default=0, null=True)),
                ('software_request', models.TextField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('a', 'Approved'), ('d', 'Denied'), ('w', 'Waiting'), ('h', 'Hold'), ('r', 'Ready For Review'), ('q', 'Response Requested'), ('i', 'Denied - Insufficient Resources'), ('x', 'Denied - Proposal Incomplete'), ('f', 'Approved - Fully Funded'), ('p', 'Approved - Partially Funded')], default='w', max_length=16)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Allocation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='allocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
