# Generated by Django 2.2.28 on 2025-03-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('from_host', models.CharField(max_length=256)),
                ('recipient_emails', models.CharField(max_length=1024)),
                ('reference_name', models.CharField(max_length=256)),
                ('email_object', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MailNotifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('event', models.CharField(choices=[('account_created_from_request', 'account_created_from_request'), ('account_request_approved', 'account_request_approved'), ('account_request_received', 'account_request_received'), ('allocation_created_from_request', 'allocation_created_from_request'), ('allocation_expired', 'allocation_expired'), ('allocation_expiring', 'allocation_expiring'), ('allocation_request_created_by_user', 'allocation_request_created_by_user'), ('project_created_by_user', 'project_created_by_user')], max_length=128)),
                ('mailto', models.TextField(blank=True, null=True)),
                ('cc', models.TextField(blank=True, null=True)),
                ('bcc', models.TextField(blank=True, null=True)),
                ('from_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=256)),
                ('body', models.TextField()),
            ],
        ),
    ]
