# Generated by Django 4.2.20 on 2025-04-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_allocation_expiration_mailer_field_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailnotifier',
            name='event',
            field=models.CharField(choices=[('account_created_from_request', 'account_created_from_request'), ('account_request_approved', 'account_request_approved'), ('account_request_received', 'account_request_received'), ('allocation_created_from_request', 'allocation_created_from_request'), ('allocation_expired', 'allocation_expired'), ('allocation_expiring', 'allocation_expiring'), ('allocation_request_created_by_user', 'allocation_request_created_by_user'), ('project_created_by_user', 'project_created_by_user')], max_length=128),
        ),
        migrations.AlterField(
            model_name='mailnotifier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
