# Generated by Django 3.2.25 on 2025-02-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_auto_20241014_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailnotifier',
            name='event',
            field=models.CharField(choices=[('__warningregistry__', '__warningregistry__'), ('account_created_from_request', 'account_created_from_request'), ('account_request_approved', 'account_request_approved'), ('account_request_received', 'account_request_received'), ('allocation_created_from_request', 'allocation_created_from_request'), ('allocation_expired', 'allocation_expired'), ('allocation_expiring', 'allocation_expiring'), ('allocation_request_created_by_user', 'allocation_request_created_by_user'), ('project_created_by_user', 'project_created_by_user')], max_length=128),
        ),
    ]
