# Generated by Django 2.2.28 on 2025-03-05 03:30

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ldapdb.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsuLdapUser',
            fields=[
                ('dn', ldapdb.models.fields.CharField(db_column='dn', max_length=200, primary_key=True, serialize=False)),
                ('first_name', ldapdb.models.fields.CharField(db_column='givenName', max_length=200)),
                ('last_name', ldapdb.models.fields.CharField(db_column='sn', max_length=200)),
                ('full_name', ldapdb.models.fields.CharField(db_column='cn', max_length=200)),
                ('email', ldapdb.models.fields.CharField(db_column='mail', max_length=200)),
                ('username', ldapdb.models.fields.CharField(db_column='sAMAccountName', max_length=200)),
                ('modified_date', ldapdb.models.fields.DateTimeField(blank=True, db_column='modifytimestamp')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuLdapUser',
            fields=[
                ('dn', ldapdb.models.fields.CharField(db_column='dn', max_length=200, primary_key=True, serialize=False)),
                ('first_name', ldapdb.models.fields.CharField(db_column='givenName', max_length=200)),
                ('last_name', ldapdb.models.fields.CharField(db_column='sn', max_length=200)),
                ('full_name', ldapdb.models.fields.CharField(db_column='cn', max_length=200)),
                ('email', ldapdb.models.fields.CharField(db_column='mail', max_length=200)),
                ('username', ldapdb.models.fields.CharField(db_column='uid', max_length=200)),
                ('modified_date', ldapdb.models.fields.DateTimeField(blank=True, db_column='modifytimestamp')),
                ('uid', ldapdb.models.fields.IntegerField(db_column='uidNumber', unique=True)),
                ('edu_affiliation', ldapdb.models.fields.ListField(db_column='eduPersonAffiliation')),
                ('edu_primary_affiliation', ldapdb.models.fields.CharField(db_column='eduPersonPrimaryAffiliation', max_length=200)),
                ('cu_primary_major', ldapdb.models.fields.CharField(db_column='cuEduPersonPrimaryMajor1', max_length=200)),
                ('cu_home_department', ldapdb.models.fields.CharField(db_column='cuEduPersonHomeDepartment', max_length=200)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RcLdapGroup',
            fields=[
                ('dn', ldapdb.models.fields.CharField(db_column='dn', max_length=200, primary_key=True, serialize=False)),
                ('gid', ldapdb.models.fields.IntegerField(blank=True, db_column='gidNumber', null=True)),
                ('name', ldapdb.models.fields.CharField(db_column='cn', max_length=200)),
                ('members', ldapdb.models.fields.ListField(blank=True, db_column='memberUid', null=True)),
            ],
            options={
                'verbose_name': 'LDAP group',
                'verbose_name_plural': 'LDAP groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RcLdapUser',
            fields=[
                ('dn', ldapdb.models.fields.CharField(db_column='dn', max_length=200, primary_key=True, serialize=False)),
                ('first_name', ldapdb.models.fields.CharField(db_column='givenName', max_length=200)),
                ('last_name', ldapdb.models.fields.CharField(db_column='sn', max_length=200)),
                ('full_name', ldapdb.models.fields.CharField(db_column='cn', max_length=200)),
                ('email', ldapdb.models.fields.CharField(db_column='mail', max_length=200)),
                ('username', ldapdb.models.fields.CharField(db_column='uid', max_length=200)),
                ('modified_date', ldapdb.models.fields.DateTimeField(blank=True, db_column='modifytimestamp')),
                ('expires', ldapdb.models.fields.IntegerField(blank=True, db_column='shadowExpire', null=True)),
                ('uid', ldapdb.models.fields.IntegerField(blank=True, db_column='uidNumber', null=True)),
                ('gid', ldapdb.models.fields.IntegerField(blank=True, db_column='gidNumber', null=True)),
                ('gecos', ldapdb.models.fields.CharField(db_column='gecos', default='', max_length=200)),
                ('home_directory', ldapdb.models.fields.CharField(db_column='homeDirectory', max_length=200)),
                ('login_shell', ldapdb.models.fields.CharField(db_column='loginShell', default='/bin/bash', max_length=200)),
                ('role', ldapdb.models.fields.ListField(blank=True, db_column='curcRole', null=True)),
                ('affiliation', ldapdb.models.fields.ListField(blank=True, db_column='curcAffiliation', null=True)),
            ],
            options={
                'verbose_name': 'LDAP user',
                'verbose_name_plural': 'LDAP users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=48)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization', models.CharField(choices=[('ucb', 'University of Colorado Boulder'), ('csu', 'Colorado State University'), ('xsede', 'XSEDE'), ('amc', 'University of Colorado Denver | Anschutz Medical Campus'), ('ncar', 'NCAR'), ('internal', 'Research Computing - Administrative')], max_length=128)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('role', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postdoc', 'Post Doc'), ('instructor', 'Instructor'), ('faculty', 'Faculty'), ('affiliated_faculty', 'Affiliated Faculty'), ('staff', 'Staff'), ('sponsored', 'Sponsored Affiliate')], default='undergraduate', max_length=24)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('d', 'Denied'), ('i', 'Incomplete')], default='p', max_length=16)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('id_verified_by', models.CharField(blank=True, max_length=128, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('login_shell', models.CharField(choices=[('/bin/bash', 'bash'), ('/bin/tcsh', 'tcsh')], default='/bin/bash', max_length=24)),
                ('resources_requested', models.CharField(blank=True, max_length=256, null=True)),
                ('sponsor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('course_number', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'unique_together': {('username', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='ComanageUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('co_person_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('group_names', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comanage User',
                'verbose_name_plural': 'Comanage Users',
            },
        ),
        migrations.CreateModel(
            name='IdTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=12, unique=True)),
                ('min_id', models.IntegerField()),
                ('max_id', models.IntegerField()),
                ('next_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ID tracker',
                'verbose_name_plural': 'ID trackers',
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_summit', models.BooleanField(default=False)),
                ('reason_course', models.BooleanField(default=False)),
                ('reason_petalibrary', models.BooleanField(default=False)),
                ('reason_blanca', models.BooleanField(default=False)),
                ('sponsor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('course_instructor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('course_number', models.CharField(blank=True, max_length=128, null=True)),
                ('summit_description', models.TextField(blank=True, null=True)),
                ('summit_funding', models.TextField(blank=True, null=True)),
                ('summit_pi_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('account_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ComanageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('gid', models.IntegerField(unique=True)),
                ('members', models.ManyToManyField(blank=True, to='accounts.ComanageUser')),
            ],
            options={
                'verbose_name': 'Comanage Group',
                'verbose_name_plural': 'Comanage Groups',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
