# Generated by Django 2.2.28 on 2025-03-05 01:01

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180228_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComanageUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('co_person_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('group_names', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comanage User',
                'verbose_name_plural': 'Comanage Users',
            },
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='login_shell',
            field=models.CharField(choices=[('/bin/bash', 'bash'), ('/bin/tcsh', 'tcsh')], default='/bin/bash', max_length=24),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='organization',
            field=models.CharField(choices=[('ucb', 'University of Colorado Boulder'), ('csu', 'Colorado State University'), ('xsede', 'XSEDE'), ('amc', 'University of Colorado Denver | Anschutz Medical Campus'), ('ncar', 'NCAR'), ('internal', 'Research Computing - Administrative')], max_length=128),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='role',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postdoc', 'Post Doc'), ('instructor', 'Instructor'), ('faculty', 'Faculty'), ('affiliated_faculty', 'Affiliated Faculty'), ('staff', 'Staff'), ('sponsored', 'Sponsored Affiliate')], default='undergraduate', max_length=24),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('d', 'Denied'), ('i', 'Incomplete')], default='p', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='ComanageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('gid', models.IntegerField(unique=True)),
                ('members', models.ManyToManyField(blank=True, to='accounts.ComanageUser')),
            ],
            options={
                'verbose_name': 'Comanage Group',
                'verbose_name_plural': 'Comanage Groups',
            },
        ),
    ]
