# Generated by Django 4.2.20 on 2025-04-02 13:58

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180228_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='discipline',
            field=models.CharField(blank=True, choices=[('Computer & Information Services', 'Computer & Information Services'), ('Engineering', 'Engineering'), ('Geosciences, Atmospheric Sciences & Ocean Sciences', 'Geosciences, Atmospheric Sciences & Ocean Sciences'), ('Life Sciences', 'Life Sciences'), ('Mathematics and Statistics', 'Mathematics and Statistics'), ('Physical Sciences', 'Physical Sciences'), ('Psychology', 'Psychology'), ('Social Sciences', 'Social Sciences'), ('Other Sciences (not elsewhere classified)', 'Other Sciences (not elsewhere classified)'), ('Education', 'Education'), ('Law', 'Law'), ('Humanities', 'Humanities'), ('Visual & Performing Arts', 'Visual & Performing Arts'), ('Business Management and Business Administration', 'Business Management and Business Administration'), ('Communications, Communications Technologies, Journalism (Library Science is considered “Other Non-Science & Engineering Fields”)', 'Communications, Communications Technologies, Journalism (Library Science is considered “Other Non-Science & Engineering Fields”)'), ('Social Work', 'Social Work'), ('Other Non-Science & Engineering Fields', 'Other Non-Science & Engineering Fields')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='login_shell',
            field=models.CharField(choices=[('/bin/bash', 'bash'), ('/bin/tcsh', 'tcsh')], default='/bin/bash', max_length=24),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='organization',
            field=models.CharField(choices=[('ucb', 'University of Colorado Boulder'), ('csu', 'Colorado State University'), ('xsede', 'XSEDE'), ('amc', 'University of Colorado Denver | Anschutz Medical Campus'), ('ncar', 'NCAR'), ('internal', 'Research Computing - Administrative')], max_length=128),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='role',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postdoc', 'Post Doc'), ('instructor', 'Instructor'), ('faculty', 'Faculty'), ('affiliated_faculty', 'Affiliated Faculty'), ('staff', 'Staff'), ('sponsored', 'Sponsored Affiliate')], default='undergraduate', max_length=24),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('d', 'Denied'), ('i', 'Incomplete')], default='p', max_length=16),
        ),
        migrations.AlterField(
            model_name='idtracker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
