name: Build RCAMP and run unit tests
on: [push, pull_request]
jobs:
  run_rcamp_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        export UWSGI_UID=$(id -u)
        export UWSGI_GID=$(id -g)
        docker-compose build
        docker-compose up -d
        docker-compose exec rcamp-uwsgi bash -c 'sleep 30s && python manage.py migrate'

    - name: Run Tests
      run: docker-compose exec rcamp-uwsgi python3 manage.py test

    - name: Stop Containers
      run: docker-compose down --remove-orphans
